### ISSUE TITLE
Repository location

### ISSUE THREAD

**Issue by nickjmv** [lebenitza/charts#1]
How do I add your repo to helm? Or is your code still based on the stable repository, which is depreciated?

Shouldn't I be able to do this?
`helm repo add lebenitza https://lebenitza.github.io/charts`

**Comment by nickjmv** [comment]
Apparently I made a typo on my terminal, the above command does work.

**Comment by lebenitza** [comment]
Hey, glad you were able to fix your problem. I will continue to provide any required help with this chart as I also use it extensively and I could not find anyone else maintaining it.
