### ISSUE TITLE
Unable to create client connection to Elasticsearch

### ISSUE THREAD

**Issue by zohairraza** [lebenitza/charts#15]
Hello Lebenitza

With reference to issue reported here
https://github.com/elastic/curator/issues/1614

it seems the image in your chart needs customisation. I see you are using https://github.com/bitnami/bitnami-docker-elasticsearch-curator which is archived and not sure if the latest version 5.8.4-debian-11-r11 has supported ES client. I think best would be to create a custom image.

**Comment by zohairraza** [comment]
Sorry, I just realised it will be a problem for the newer versions of ES if we use old library. Closing this ticket, I will rather try upgrading the ES

**Comment by lebenitza** [comment]
Feel like the elasticsearch team wants us to move away from [curator](https://github.com/elastic/curator) as the project does not seem to receive much attention. Maybe this is why the bitnami docker image is deprecated as well.

**Comment by zohairraza** [comment]
yeah after the ILM policies
